### ISSUE TITLE
A5 and A6 configuration

### ISSUE THREAD

**Issue by johnty** [BITalinoWorld/cpp-api#1]
It seems like by default A5 and A6 are not reporting correct values. All other channels work fine. Is there some additional setting that needs to be done to read data on these two channels properly? For example, the [Max external](https://github.com/Ircam-RnD/bitalino-max), which makes use of this API, does not work for A5 and A6, but I see using OpenSignals that these two last channels appear to report data fine.

**Comment by johnty** [comment]
update: after snooping around a bit, I see that A5 and 6 are only 6 bit values instead of 10. so perhaps the result is as originally intended...

**Comment by filipecsilva** [comment]
Hi @johnty, that's right: A5 and A6 have a resolution of 6 bits instead of 10 bits when 5 or 6 channels are selected for acquisition. The default on the API is to have all 6 channels selected.
This is explained in page 2 (section Data Packets) of the BITalino MCU datasheet  available at
https://bitalino.com/datasheets/REVOLUTION_MCU_Block_Datasheet.pdf
and also on page 21 of the OpenSignals manual (page 22 of the PDF) available at
https://bitalino.com/downloads/int-releases/OpenSignals_(r)evolution_Manual.pdf
